// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



package org.usfirst.frc6468.cubeMover2001;

import org.usfirst.frc6468.cubeMover2001.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.XboxController;
import edu.wpi.first.wpilibj.buttons.*;
import org.usfirst.frc6468.cubeMover2001.subsystems.*;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 *
 *@author Will English
 *@author Aditya 
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


	hand = new GenericHID.hand;
	joystickHand = new GenericHID.hand;
	left = hand.kLeft;
	right = hand.kRight;
    public Xbox gamePad;

    public JoystickButton climbButton;
   



    public OI() {
    	
    	/**
    	 * XBox controller object
    	 */
    	gamePad = new XboxController(0);
    	/**
    	 * Joystick object
    	 */
    	joystick = new Joystick(1);
    	/**
    	 * Writes value of the right bumper to var rightBump
    	 */
    	rightBump = gamePad.getBumper(right);
    	/**
    	 * Writes value of the left bumper to var leftBump
    	 */
        leftBump = gamePad.getBumper(left);
    	/**
    	 * new joystick button object
    	 */
        climbButton = new JoystickButton(joystick, 3);


        double LStickY = gamepad.getY(left);
        boolean rightBump = getBumper(right);
        boolean leftBump = getBumper(left);
        boolean joyTrig = joystick.getTrigger();
        boolean climbPressed = joystick.getButton(climbButton);
        
        if(LStickY != 0) new driveStraight();
        if(rightBump == true) new slideRight();
        if(leftBump == true) new slideLeft();
        if(joystick.getAxis(kY) > 0) new liftUp();  
        if(joystick.getAxis(kY) < 0) new dropDown();
       
        
        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous", new Autonomous());
        SmartDashboard.putData("closeClaw", new closeClaw());
        SmartDashboard.putData("driveStraight", new driveStraight());
        SmartDashboard.putData("slideLeft", new slideLeft());
        SmartDashboard.putData("slideRight", new slideRight());
        SmartDashboard.putData("moveWithSticks", new moveWithSticks());
        SmartDashboard.putData("liftUp", new liftUp());
        SmartDashboard.putData("dropDown", new dropDown());
        SmartDashboard.putData("climb", new climb());

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

 
    public Joystick getXBox() {
        return xBox;
    }

    public Joystick getJoystick2() {
        return joystick2;
    }

    public Joystick getJoystick3() {
        return joystick3;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

