// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package src.org.usfirst.frc6468.cubeMover2001.robot;


import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Servo;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.Talon;

import edu.wpi.first.wpilibj.SpeedController;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 *This file maps ports and puts our hardware on the LiveWindow
 *
 *@version 1.0
 *@author Will English
 */
@SuppressWarnings("deprecation")

public class RobotMap {
    public static SpeedController slideTrainslider;
    public static SpeedController slideTrainleftSide;
    public static SpeedController slideTrainrightSide;
    public static RobotDrive slideTrainRobotDrive;
    public static SpeedController verticalLiftliftMotor;
    public static Servo clawclawServo;


	public static void init() {
        slideTrainslider = new Talon(0);
        LiveWindow.addActuator("slideTrain", "slider", (Spark) slideTrainslider);
        
        slideTrainleftSide = new Talon(1);
        LiveWindow.addActuator("slideTrain", "leftSide", (Spark) slideTrainleftSide);
        
        slideTrainrightSide = new Talon(2);
        LiveWindow.addActuator("slideTrain", "rightSide", (Spark) slideTrainrightSide);
        
        slideTrainRobotDrive = new RobotDrive(slideTrainleftSide, slideTrainrightSide);
        
        slideTrainRobotDrive.setSafetyEnabled(true);
        slideTrainRobotDrive.setExpiration(0.1);
        slideTrainRobotDrive.setSensitivity(0.5);
        slideTrainRobotDrive.setMaxOutput(1.0);

        verticalLiftliftMotor = new Spark(3);
        LiveWindow.addActuator("verticalLift", "liftMotor", (Spark) verticalLiftliftMotor);
        
        clawclawServo = new Servo(4);
        LiveWindow.addActuator("claw", "clawServo", clawclawServo);
        

    }
}
